### ISSUE TITLE
Groupby query 6 can't be run

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/h2o-benchmarks#5]
Today we can't run [query 6](https://github.com/h2oai/db-benchmark/blob/c7421051af7530951d16b1505158371aebc0d2c1/dask/groupby-dask2.py#L192-L218) because Dask DataFrames don't implement `median`. We should add a `DataFrame.median` method. See https://github.com/dask/dask/issues/4362 for an upstream discussion in `dask/dask`

**Comment by ncclementi** [comment]
I added the query to the runtime repo. https://github.com/coiled/coiled-runtime/pull/459

**Comment by jrbourbeau** [comment]
Closed via https://github.com/coiled/coiled-runtime/pull/459 +  https://github.com/coiled/h2o-benchmarks/pull/19
